### ISSUE TITLE
Perhaps add a link to the talk on YouTube?

### ISSUE THREAD

**Issue by noamraph** [rust-lang/polonius#191]
Hi,

I got interested in Polonius as a way to better understand the borrow checker. I tried to read the blog post but didn't manage to really understand. The great talk https://youtu.be/_agDeiWek8w helped me understand the motivation and the basic principle. Perhaps add a link to it to the README?

Thanks!
Noam

**Comment by lqd** [comment]
We could, but it’s already in the book linked in the readme, and it contains a lot more more documentation as well as a link to that talk (https://rust-lang.github.io/polonius/see_also.html) and to blog posts for example.

**Comment by noamraph** [comment]
@lqd I think it's very hard to find the talk right now. If I want to get an idea about what Polonius is, I would go to the blog post, not to the book, since the README says:
> It implements the analysis [described in this blogpost](http://smallcultfollowing.com/babysteps/blog/2018/04/27/an-alias-based-formulation-of-the-borrow-checker/). Details are [in the Polonius book](https://rust-lang.github.io/polonius/).
I would first go to the blog post to understand, not to the book to get the details. And even following the book link, it's under "See Also".

I think that perhaps the best thing for me would have been if @nikomatsakis added a note at the beginning of the blog post, saying that for a gentler introduction you could watch the talk. Then I would have immediately found it, since the README forwards to the blog post for an introduction.

**Comment by lqd** [comment]
How about changing the first link like this: "it implements the analysis described in these blogposts and talks", pointing to the See Also page ?

**Comment by noamraph** [comment]
@lqd the "see also" page lists quite a lot of links, most of them for people already familiar with the general idea. I like how there is a specific link for the introduction. That's why I like either having just two links ("described in this blog post and in this link") or adding a link to the talk at the beginning of the blog post.

**Comment by lqd** [comment]
Why not. I'd like to avoid bothering niko for this though, so I'd gladly merge a PR with the first suggestion.

**Comment by noamraph** [comment]
@lqd Cool! How is this PR? https://github.com/rust-lang/polonius/pull/192

**Comment by lqd** [comment]
Great, thank you! Let's close this then.

**Comment by noamraph** [comment]
@lqd thank you! It's good to feel that I made a tiny contribution to making this more accessible.
